version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_DRIVER: postgres
      DB_HOSTNAME: postgres
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: development
      DB_SCHEMA: nestjs-boilerplate
      JWT_SECRET: development
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: development
      POSTGRES_DB: nestjs-boilerplate
      PGDATA: /var/lib/postgres
